import { get, run } from "./index.js";

interface MockShipment {
  tracking_number: string;
  scanned_at: string;
  scanned_by: string;
  delivery_type: string;
  zone_id: number | null;
  status_id: number;
  management_id: number;
  recipient_name: string;
  recipient_phone: string;
  payment_desc: string;
  amount_total: number;
  amount_declared: number;
  amount_to_collect: number;
  api_current_state_desc: string;
  api_current_city: string;
  api_current_state_at: string;
  gestion_count: number;
  checkout_date?: string | null;
  checkout_by?: number | null;
}

interface MockTrackingRow {
  tracking_number: string;
  ciudad: string;
  descripcion_estado: string;
  fecha_cambio_estado: string;
  bodega: string;
  motivo: string;
  mensajero: string;
  numero_tipo_impreso: string;
  descripcion_tipo_impreso: string;
  usuario: string;
  observacion: string;
  has_location_icon: number;
}

const mockShipments: MockShipment[] = [
  {
    tracking_number: "001862095920",
    scanned_at: "2026-03-14T08:12:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 1,
    management_id: 1,
    recipient_name: "Laura Montoya",
    recipient_phone: "3001112233",
    payment_desc: "Contado",
    amount_total: 18000,
    amount_declared: 18000,
    amount_to_collect: 0,
    api_current_state_desc: "En oficina",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T08:20:00.000Z",
    gestion_count: 0,
  },
  {
    tracking_number: "001862095921",
    scanned_at: "2026-03-14T08:20:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 1,
    management_id: 1,
    recipient_name: "Maria Angelica Rios",
    recipient_phone: "3001112234",
    payment_desc: "Contraentrega",
    amount_total: 24500,
    amount_declared: 20000,
    amount_to_collect: 24500,
    api_current_state_desc: "En ruta de entrega",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T08:30:00.000Z",
    gestion_count: 1,
  },
  {
    tracking_number: "001862095922",
    scanned_at: "2026-03-14T08:28:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 1,
    management_id: 1,
    recipient_name: "Carlos Bedoya",
    recipient_phone: "3001112235",
    payment_desc: "Contado",
    amount_total: 19500,
    amount_declared: 19500,
    amount_to_collect: 0,
    api_current_state_desc: "En ruta de entrega",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T08:35:00.000Z",
    gestion_count: 2,
  },
  {
    tracking_number: "001862095923",
    scanned_at: "2026-03-14T08:35:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 2,
    status_id: 1,
    management_id: 1,
    recipient_name: "Diana Sepulveda",
    recipient_phone: "3001112236",
    payment_desc: "Contraentrega",
    amount_total: 32000,
    amount_declared: 28000,
    amount_to_collect: 32000,
    api_current_state_desc: "En oficina",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T08:40:00.000Z",
    gestion_count: 3,
  },
  {
    tracking_number: "001862095924",
    scanned_at: "2026-03-14T08:42:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 2,
    status_id: 1,
    management_id: 1,
    recipient_name: "Andres Oquendo",
    recipient_phone: "3001112237",
    payment_desc: "Contado",
    amount_total: 21000,
    amount_declared: 21000,
    amount_to_collect: 0,
    api_current_state_desc: "En oficina",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T08:45:00.000Z",
    gestion_count: 1,
  },
  {
    tracking_number: "001862095925",
    scanned_at: "2026-03-14T08:50:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 3,
    status_id: 1,
    management_id: 1,
    recipient_name: "Daniela Ruiz",
    recipient_phone: "3001112238",
    payment_desc: "Contraentrega",
    amount_total: 41000,
    amount_declared: 39000,
    amount_to_collect: 41000,
    api_current_state_desc: "En oficina",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T08:52:00.000Z",
    gestion_count: 0,
  },
  {
    tracking_number: "001862095926",
    scanned_at: "2026-03-14T08:58:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 1,
    management_id: 1,
    recipient_name: "Santiago Perez",
    recipient_phone: "3001112239",
    payment_desc: "Contado",
    amount_total: 15000,
    amount_declared: 15000,
    amount_to_collect: 0,
    api_current_state_desc: "En ruta de entrega",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T09:00:00.000Z",
    gestion_count: 2,
  },
  {
    tracking_number: "001862095927",
    scanned_at: "2026-03-14T09:05:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 2,
    status_id: 2,
    management_id: 2,
    recipient_name: "Leiddy Oquendo",
    recipient_phone: "3001112240",
    payment_desc: "Contraentrega",
    amount_total: 28000,
    amount_declared: 25000,
    amount_to_collect: 28000,
    api_current_state_desc: "Entrega exitosa",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T09:10:00.000Z",
    gestion_count: 0,
    checkout_date: "2026-03-14T09:10:00.000Z",
    checkout_by: null,
  },
  {
    tracking_number: "001862095928",
    scanned_at: "2026-03-14T09:12:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 1,
    management_id: 1,
    recipient_name: "Valentina Giraldo",
    recipient_phone: "3001112241",
    payment_desc: "Contado",
    amount_total: 17000,
    amount_declared: 17000,
    amount_to_collect: 0,
    api_current_state_desc: "En oficina",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T09:15:00.000Z",
    gestion_count: 3,
  },
  {
    tracking_number: "001862095929",
    scanned_at: "2026-03-14T09:20:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 3,
    status_id: 1,
    management_id: 1,
    recipient_name: "Jhon Cardenas",
    recipient_phone: "3001112242",
    payment_desc: "Contraentrega",
    amount_total: 36500,
    amount_declared: 32000,
    amount_to_collect: 36500,
    api_current_state_desc: "En oficina",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-14T09:22:00.000Z",
    gestion_count: 1,
  },
];

const archivedMockShipments: MockShipment[] = [
  {
    tracking_number: "001862095930",
    scanned_at: "2026-02-28T08:10:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 2,
    management_id: 2,
    recipient_name: "Camila Torres",
    recipient_phone: "3002112233",
    payment_desc: "Contado",
    amount_total: 22000,
    amount_declared: 22000,
    amount_to_collect: 0,
    api_current_state_desc: "Entrega exitosa",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-01T10:00:00.000Z",
    gestion_count: 0,
    checkout_date: "2026-03-01T10:00:00.000Z",
  },
  {
    tracking_number: "001862095931",
    scanned_at: "2026-02-27T09:00:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 2,
    status_id: 2,
    management_id: 3,
    recipient_name: "Julian Mena",
    recipient_phone: "3002112234",
    payment_desc: "Contraentrega",
    amount_total: 38000,
    amount_declared: 34000,
    amount_to_collect: 38000,
    api_current_state_desc: "Devuelto",
    api_current_city: "URRAO",
    api_current_state_at: "2026-03-01T16:00:00.000Z",
    gestion_count: 2,
    checkout_date: "2026-03-01T16:00:00.000Z",
  },
  {
    tracking_number: "001862095932",
    scanned_at: "2026-02-26T09:20:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 2,
    management_id: 2,
    recipient_name: "Paola Valencia",
    recipient_phone: "3002112235",
    payment_desc: "Contado",
    amount_total: 16000,
    amount_declared: 16000,
    amount_to_collect: 0,
    api_current_state_desc: "Entrega exitosa",
    api_current_city: "URRAO",
    api_current_state_at: "2026-02-27T11:30:00.000Z",
    gestion_count: 1,
    checkout_date: "2026-02-27T11:30:00.000Z",
  },
  {
    tracking_number: "001862095933",
    scanned_at: "2026-02-25T07:40:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 3,
    status_id: 2,
    management_id: 2,
    recipient_name: "Harold Ruiz",
    recipient_phone: "3002112236",
    payment_desc: "Contraentrega",
    amount_total: 47000,
    amount_declared: 42000,
    amount_to_collect: 47000,
    api_current_state_desc: "Entrega exitosa",
    api_current_city: "URRAO",
    api_current_state_at: "2026-02-26T14:50:00.000Z",
    gestion_count: 3,
    checkout_date: "2026-02-26T14:50:00.000Z",
  },
  {
    tracking_number: "001862095934",
    scanned_at: "2026-02-24T10:00:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 2,
    management_id: 3,
    recipient_name: "Martha Ospina",
    recipient_phone: "3002112237",
    payment_desc: "Contado",
    amount_total: 23000,
    amount_declared: 23000,
    amount_to_collect: 0,
    api_current_state_desc: "Devuelto",
    api_current_city: "URRAO",
    api_current_state_at: "2026-02-25T12:00:00.000Z",
    gestion_count: 1,
    checkout_date: "2026-02-25T12:00:00.000Z",
  },
  {
    tracking_number: "001862095935",
    scanned_at: "2026-02-23T11:15:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 2,
    status_id: 2,
    management_id: 2,
    recipient_name: "Sebastian Restrepo",
    recipient_phone: "3002112238",
    payment_desc: "Contraentrega",
    amount_total: 31000,
    amount_declared: 28000,
    amount_to_collect: 31000,
    api_current_state_desc: "Entrega exitosa",
    api_current_city: "URRAO",
    api_current_state_at: "2026-02-24T13:00:00.000Z",
    gestion_count: 0,
    checkout_date: "2026-02-24T13:00:00.000Z",
  },
  {
    tracking_number: "001862095936",
    scanned_at: "2026-02-22T08:45:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 1,
    status_id: 2,
    management_id: 3,
    recipient_name: "Gloria Velez",
    recipient_phone: "3002112239",
    payment_desc: "Contado",
    amount_total: 14000,
    amount_declared: 14000,
    amount_to_collect: 0,
    api_current_state_desc: "Devuelto",
    api_current_city: "URRAO",
    api_current_state_at: "2026-02-23T15:20:00.000Z",
    gestion_count: 2,
    checkout_date: "2026-02-23T15:20:00.000Z",
  },
  {
    tracking_number: "001862095937",
    scanned_at: "2026-02-21T09:35:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 3,
    status_id: 2,
    management_id: 2,
    recipient_name: "Ana Sofia Jaramillo",
    recipient_phone: "3002112240",
    payment_desc: "Contraentrega",
    amount_total: 52000,
    amount_declared: 50000,
    amount_to_collect: 52000,
    api_current_state_desc: "Entrega exitosa",
    api_current_city: "URRAO",
    api_current_state_at: "2026-02-22T09:55:00.000Z",
    gestion_count: 2,
    checkout_date: "2026-02-22T09:55:00.000Z",
  },
  {
    tracking_number: "001862095938",
    scanned_at: "2026-02-20T12:10:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "LOCAL",
    zone_id: 2,
    status_id: 2,
    management_id: 3,
    recipient_name: "Pedro Zapata",
    recipient_phone: "3002112241",
    payment_desc: "Contado",
    amount_total: 19000,
    amount_declared: 19000,
    amount_to_collect: 0,
    api_current_state_desc: "Devuelto",
    api_current_city: "URRAO",
    api_current_state_at: "2026-02-21T17:10:00.000Z",
    gestion_count: 3,
    checkout_date: "2026-02-21T17:10:00.000Z",
  },
  {
    tracking_number: "001862095939",
    scanned_at: "2026-02-19T08:30:00.000Z",
    scanned_by: "MOCK_LOCAL",
    delivery_type: "ZONA",
    zone_id: 1,
    status_id: 2,
    management_id: 2,
    recipient_name: "Natalia Cano",
    recipient_phone: "3002112242",
    payment_desc: "Contraentrega",
    amount_total: 26000,
    amount_declared: 24000,
    amount_to_collect: 26000,
    api_current_state_desc: "Entrega exitosa",
    api_current_city: "URRAO",
    api_current_state_at: "2026-02-20T10:40:00.000Z",
    gestion_count: 1,
    checkout_date: "2026-02-20T10:40:00.000Z",
  },
];

const mockTrackingRows: MockTrackingRow[] = [
  {
    tracking_number: "001862095921",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "13/03/2026 9:12:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "RESIDENTE AUSENTE",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095922",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "12/03/2026 10:30:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "REHUSADO",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095922",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "13/03/2026 2:10:00 p. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "NO CONTESTA",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095923",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "11/03/2026 9:00:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "RESIDENTE AUSENTE",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095923",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "12/03/2026 10:15:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "REHUSADO",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095923",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "13/03/2026 4:45:00 p. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "NO CUENTA CON EL DINERO",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095924",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "13/03/2026 11:05:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "NOTIFICACION",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095926",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "12/03/2026 8:00:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "AUSENTE",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095926",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "13/03/2026 1:20:00 p. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "REHUSADO",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095927",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "Entrega Exitosa",
    fecha_cambio_estado: "14/03/2026 9:10:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Entregado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095928",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "11/03/2026 9:00:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "AUSENTE",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095928",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "12/03/2026 11:30:00 a. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "REHUSADO",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095928",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "13/03/2026 3:40:00 p. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "NO CONTESTA",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
  {
    tracking_number: "001862095929",
    ciudad: "URRAO/ANT/COL",
    descripcion_estado: "En Proceso de Devolucion",
    fecha_cambio_estado: "13/03/2026 5:10:00 p. m.",
    bodega: "5210 / AGE / AGE",
    motivo: "NOTIFICACION",
    mensajero: "",
    numero_tipo_impreso: "0",
    descripcion_tipo_impreso: "Planilla Asignacion Mensajero",
    usuario: "mock.local",
    observacion: "Descargado desde APP",
    has_location_icon: 1,
  },
];

export function seedMockShipmentsIfNeeded(): void {
  if (process.env.ENABLE_APX_SCRAPER !== "false") {
    return;
  }

  const existingOpenMock = get<{ count: number }>(
    "SELECT COUNT(*) as count FROM shipments WHERE tracking_number LIKE '00%' AND COALESCE(status_id, 1) != 2"
  );
  const existingClosedMock = get<{ count: number }>(
    "SELECT COUNT(*) as count FROM shipments WHERE tracking_number LIKE '00%' AND status_id = 2"
  );
  const existingArchivedMock = get<{ count: number }>(
    "SELECT COUNT(*) as count FROM shipments_archive WHERE tracking_number LIKE '00%'"
  );

  if ((existingOpenMock?.count || 0) === 0) {
    console.log("[MOCK] Seeding 10 fake open shipments for local development");
    for (const shipment of mockShipments) {
      run(
        `INSERT OR IGNORE INTO shipments (
        tracking_number, created_at, updated_at, scanned_at, scanned_by,
        delivery_type, zone_id, status_id, management_id, office_status,
        recipient_name, recipient_phone, api_last_fetch_at, apx_last_fetch_at,
        api_success, api_message, api_current_state_desc, api_current_city, api_current_state_at,
        payment_code, payment_desc, amount_total, amount_declared, amount_to_collect,
        gestion_count, checkout_date
      ) VALUES (
        :tracking_number, :created_at, :updated_at, :scanned_at, :scanned_by,
        :delivery_type, :zone_id, :status_id, :management_id, 'PAQUETE_INGRESADO',
        :recipient_name, :recipient_phone, :api_last_fetch_at, :apx_last_fetch_at,
        1, 'MOCK_OK', :api_current_state_desc, :api_current_city, :api_current_state_at,
        1, :payment_desc, :amount_total, :amount_declared, :amount_to_collect,
        :gestion_count, :checkout_date
        )`,
        {
          ":tracking_number": shipment.tracking_number,
          ":created_at": shipment.scanned_at,
          ":updated_at": shipment.scanned_at,
          ":scanned_at": shipment.scanned_at,
          ":scanned_by": shipment.scanned_by,
          ":delivery_type": shipment.delivery_type,
          ":zone_id": shipment.zone_id,
          ":status_id": shipment.status_id,
          ":management_id": shipment.management_id,
          ":recipient_name": shipment.recipient_name,
          ":recipient_phone": shipment.recipient_phone,
          ":api_last_fetch_at": shipment.scanned_at,
          ":apx_last_fetch_at": shipment.scanned_at,
          ":api_current_state_desc": shipment.api_current_state_desc,
          ":api_current_city": shipment.api_current_city,
          ":api_current_state_at": shipment.api_current_state_at,
          ":payment_desc": shipment.payment_desc,
          ":amount_total": shipment.amount_total,
          ":amount_declared": shipment.amount_declared,
          ":amount_to_collect": shipment.amount_to_collect,
          ":gestion_count": shipment.gestion_count,
          ":checkout_date": shipment.checkout_date || null,
        }
      );
    }
  } else {
    console.log("[MOCK] Open mock shipments already present, skipping seed");
  }

  if ((existingClosedMock?.count || 0) === 0) {
    console.log("[MOCK] Seeding 10 fake closed shipments for local development");
    for (const shipment of archivedMockShipments) {
      run(
        `INSERT OR IGNORE INTO shipments (
          tracking_number, created_at, updated_at, scanned_at, scanned_by,
          delivery_type, zone_id, status_id, management_id, office_status,
          recipient_name, recipient_phone, api_last_fetch_at, apx_last_fetch_at,
          api_success, api_message, api_current_state_desc, api_current_city, api_current_state_at,
          payment_code, payment_desc, amount_total, amount_declared, amount_to_collect,
          gestion_count, checkout_date, checkout_by
        ) VALUES (
          :tracking_number, :created_at, :updated_at, :scanned_at, :scanned_by,
          :delivery_type, :zone_id, :status_id, :management_id, 'PAQUETE_INGRESADO',
          :recipient_name, :recipient_phone, :api_last_fetch_at, :apx_last_fetch_at,
          1, 'MOCK_OK', :api_current_state_desc, :api_current_city, :api_current_state_at,
          1, :payment_desc, :amount_total, :amount_declared, :amount_to_collect,
          :gestion_count, :checkout_date, :checkout_by
        )`,
        {
          ":tracking_number": shipment.tracking_number,
          ":created_at": shipment.scanned_at,
          ":updated_at": shipment.checkout_date || shipment.scanned_at,
          ":scanned_at": shipment.scanned_at,
          ":scanned_by": shipment.scanned_by,
          ":delivery_type": shipment.delivery_type,
          ":zone_id": shipment.zone_id,
          ":status_id": shipment.status_id,
          ":management_id": shipment.management_id,
          ":recipient_name": shipment.recipient_name,
          ":recipient_phone": shipment.recipient_phone,
          ":api_last_fetch_at": shipment.scanned_at,
          ":apx_last_fetch_at": shipment.scanned_at,
          ":api_current_state_desc": shipment.api_current_state_desc,
          ":api_current_city": shipment.api_current_city,
          ":api_current_state_at": shipment.api_current_state_at,
          ":payment_desc": shipment.payment_desc,
          ":amount_total": shipment.amount_total,
          ":amount_declared": shipment.amount_declared,
          ":amount_to_collect": shipment.amount_to_collect,
          ":gestion_count": shipment.gestion_count,
          ":checkout_date": shipment.checkout_date || null,
          ":checkout_by": shipment.checkout_by || null,
        }
      );
    }
  } else {
    console.log("[MOCK] Closed mock shipments already present, skipping seed");
  }

  const existingTrackingRows = get<{ count: number }>(
    "SELECT COUNT(*) as count FROM shipment_tracking WHERE tracking_number LIKE '00%'"
  );

  if ((existingTrackingRows?.count || 0) === 0) {
    for (const row of mockTrackingRows) {
      run(
        `INSERT INTO shipment_tracking (
        tracking_number, ciudad, descripcion_estado, fecha_cambio_estado,
        bodega, motivo, mensajero, numero_tipo_impreso, descripcion_tipo_impreso,
        usuario, observacion, has_location_icon, fetched_at
      ) VALUES (
        :tracking_number, :ciudad, :descripcion_estado, :fecha_cambio_estado,
        :bodega, :motivo, :mensajero, :numero_tipo_impreso, :descripcion_tipo_impreso,
        :usuario, :observacion, :has_location_icon, :fetched_at
        )`,
        {
          ":tracking_number": row.tracking_number,
          ":ciudad": row.ciudad,
          ":descripcion_estado": row.descripcion_estado,
          ":fecha_cambio_estado": row.fecha_cambio_estado,
          ":bodega": row.bodega,
          ":motivo": row.motivo,
          ":mensajero": row.mensajero,
          ":numero_tipo_impreso": row.numero_tipo_impreso,
          ":descripcion_tipo_impreso": row.descripcion_tipo_impreso,
          ":usuario": row.usuario,
          ":observacion": row.observacion,
          ":has_location_icon": row.has_location_icon,
          ":fetched_at": "2026-03-14T09:30:00.000Z",
        }
      );
    }
  }

  if ((existingArchivedMock?.count || 0) === 0) {
    console.log("[MOCK] Seeding 10 fake archived shipments for local development");
    for (const shipment of archivedMockShipments) {
      run(
        `INSERT OR IGNORE INTO shipments_archive (
          tracking_number, archived_at, created_at, updated_at, scanned_at, scanned_by,
          delivery_type, zone_id, status_id, management_id, office_status,
          client_name, client_phone, checkout_date, checkout_by, message_sent,
          recipient_name, recipient_id, recipient_phone, api_last_fetch_at, apx_last_fetch_at,
          api_success, api_message, api_current_state_id, api_current_state_desc, api_current_city, api_current_state_at,
          payment_code, payment_desc, amount_total, amount_declared, amount_to_collect, gestion_count
        ) VALUES (
          :tracking_number, :archived_at, :created_at, :updated_at, :scanned_at, :scanned_by,
          :delivery_type, :zone_id, :status_id, :management_id, 'PAQUETE_INGRESADO',
          NULL, NULL, :checkout_date, :checkout_by, 0,
          :recipient_name, NULL, :recipient_phone, :api_last_fetch_at, :apx_last_fetch_at,
          1, 'MOCK_OK', NULL, :api_current_state_desc, :api_current_city, :api_current_state_at,
          1, :payment_desc, :amount_total, :amount_declared, :amount_to_collect, :gestion_count
        )`,
        {
          ":tracking_number": shipment.tracking_number,
          ":archived_at": shipment.checkout_date || shipment.scanned_at,
          ":created_at": shipment.scanned_at,
          ":updated_at": shipment.checkout_date || shipment.scanned_at,
          ":scanned_at": shipment.scanned_at,
          ":scanned_by": shipment.scanned_by,
          ":delivery_type": shipment.delivery_type,
          ":zone_id": shipment.zone_id,
          ":status_id": shipment.status_id,
          ":management_id": shipment.management_id,
          ":checkout_date": shipment.checkout_date || null,
          ":checkout_by": shipment.checkout_by || null,
          ":recipient_name": shipment.recipient_name,
          ":recipient_phone": shipment.recipient_phone,
          ":api_last_fetch_at": shipment.scanned_at,
          ":apx_last_fetch_at": shipment.scanned_at,
          ":api_current_state_desc": shipment.api_current_state_desc,
          ":api_current_city": shipment.api_current_city,
          ":api_current_state_at": shipment.api_current_state_at,
          ":payment_desc": shipment.payment_desc,
          ":amount_total": shipment.amount_total,
          ":amount_declared": shipment.amount_declared,
          ":amount_to_collect": shipment.amount_to_collect,
          ":gestion_count": shipment.gestion_count,
        }
      );
    }
  } else {
    console.log("[MOCK] Archived mock shipments already present, skipping seed");
  }
}
